[config]
default_to_workspace = false

[tasks.objcopy]
command = "cargo"
args = [
  "objcopy",
  "${@}",
  "--",
  "-O",
  "binary",
  "${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/litex-sim-firmware.bin",
]

[tasks.simulate]
command = "litex_sim"
args = [
  "--output-dir=${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/litex_sim",
  "--cpu-variant=minimal",
  "--rom-init=${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/litex-sim-firmware.bin",
  "--non-interactive",
]
dependencies = ["objcopy"]
